apiVersion: v1
kind: Service
metadata:
  name: account-svc
spec:
  selector:
    app: account-service
  type: ClusterIP
  ports:
  - protocol: "TCP"
    port: 80 
    targetPort: 8080

---

apiVersion: v1
kind: Service
metadata:
  name: checkout-svc
spec:
  selector:
    app: checkout-service
  type: ClusterIP
  ports:
  - protocol: "TCP"
    port: 80 
    targetPort: 8080

---

apiVersion: v1
kind: Service
metadata:
  name: identity-svc
spec:
  selector:
    app: identity-service
  type: ClusterIP
  ports:
  - protocol: "TCP"
    port: 80 
    targetPort: 8080

---

apiVersion: v1
kind: Service
metadata:
  name: trip-svc
spec:
  selector:
    app: trip-service
  type: ClusterIP
  ports:
  - protocol: "TCP"
    port: 80 
    targetPort: 8080

---

apiVersion: v1
kind: Service
metadata:
  name: gateway-svc
spec:
  selector:
    app: gateway-service
  type: LoadBalancer
  ports:
  - protocol: "TCP"
    port: 80 
    targetPort: 8080

---

apiVersion: v1
kind: Service
metadata:
  name: eureka-server-svc
spec:
  selector:
    app: eureka-server
  type: LoadBalancer
  ports:
  - protocol: "TCP"
    port: 80 
    targetPort: 8761
