name: Demo

on:
  workflow_dispatch:


jobs:
  demo:
    runs-on: ubuntu-latest
    
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - run: |
          echo ${{ github.workspace }}
          ls ${{ github.workspace }}/
          
      
