name: Demo

on:
  workflow_dispatch:


jobs:
  demo:
    runs-on: ubuntu-latest
    defaults:
          run:
            working-directory: stripe-backend/
    
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - run: |
          echo ${{ github.workspace }}
          ls
          
      
