name: Deploy infra and services

on:
  workflow_dispatch:
  workflow_call:

permissions:
  id-token: write
  contents: read

jobs:
  deploy-infra:
    uses: ./.github/workflows/job-deploy-infra.yaml
    with:
      TFAction: apply

  push-images:
    uses: ./.github/workflows/job-push-images.yaml