name: Deploy services on kubernetes
on:
  workflow_dispatch:
  workflow_call:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy-k8s:
    runs-on: ubuntu-latest
    env:
      RESOURCE_GROUP: "tripbuddies-rg"
      CLUSTER_NAME: "tripbuddies-aks"

    steps:
    - name: checkout
      uses: actions/checkout@v4

    - name: Azure login
      uses: azure/login@v2
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
    
    - name: Set up kubelogin for non-interactive login
      uses: azure/use-kubelogin@v1
      with:
        kubelogin-version: 'v0.0.25'

    - name: Get K8s context
      uses: azure/aks-set-context@v3
      with:
        resource-group: ${{ env.RESOURCE_GROUP }}
        cluster-name: ${{ env.CLUSTER_NAME }}
        admin: 'false'
        use-kubelogin: 'true'
    
    - name: Replace tokens
      run: |
        sed -i "s|__ADMIN_JWT_SECRET__|${{ secrets.ADMIN_JWT_SECRET }}/g" k8s/configmap.yaml
        sed -i "s|__API_TOKEN_SALT__|${{ secrets.API_TOKEN_SALT }}|g" k8s/configmap.yaml
        sed -i "s|__APP_KEYS__|${{ secrets.APP_KEYS }}|g" k8s/configmap.yaml
        sed -i "s|__DATABASE_HOST__|${{ secrets.DATABASE_HOST }}|g" k8s/configmap.yaml
        sed -i "s|__DATABASE_PASSWORD__|${{ secrets.DATABASE_PASSWORD }}|g" k8s/configmap.yaml
        sed -i "s|__JWT_SECRET__|${{ secrets.JWT_SECRET }}|g" k8s/configmap.yaml
        sed -i "s|__TRANSFER_TOKEN_SALT__|${{ secrets.TRANSFER_TOKEN_SALT }}|g" k8s/configmap.yaml

    - name: Deploys application
      uses: Azure/k8s-deploy@v4
      with:
        action: deploy
        manifests: k8s

    
