name: Deploy infra Template

on: 
  workflow_dispatch:
    inputs:
       TFAction:
        description: 'apply or destroy infra' 
        required: true
        type: choice
        options:
          - apply
          - destroy
  workflow_call:
    inputs:
        TFAction: 
            description: 'apply or destroy infra' 
            required: true
            type: string
    
jobs:
  deploy-infra:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: IAC/dev
    env: 
      ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      ARM_TENANT_ID:  ${{ secrets.AZURE_TENANT_ID }}
      ARM_CLIENT_SECRET: ${{secrets.AZURE_CLIENT_SECRET}}

    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: Azure login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Check if storage account exists
        run: |
          az storage account show -g tripbuddies-rg -n tripbuddies
      
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2.0.3
      
      - name: Terraform Init
        run: terraform init

      - name: Terraform Format
        run: terraform fmt

      - name: Terraform Plan
        run: terraform plan 
      
      - name: Terraform apply
        if: ${{ inputs.TFAction == 'apply'}} 
        run: terraform apply -auto-approve

      - name: Terraform destroy
        if: ${{ inputs.TFAction == 'destroy'}} 
        run : terraform destroy -auto-approve

