name: PR Validation-SpringBoot 

on: 
  pull_request:
    types: [opened, reopened, synchronize]
    branches: 
    - main
    paths:
    - 'spring-backend/**'

jobs:
  pr-validation-springboot:
    uses: ./.github/workflows/job-build-services.yaml
    with: 
      directory: 'springboot'

