name: PR Validation-IAC

on: 
  workflow_dispatch:
  pull_request:
    types: [opened, reopened, synchronize]
    branches: 
    - main
    paths:
    - 'IAC/**'

jobs:
  pr-validation-springboot:
    uses: ./.github/workflows/job-build-services.yaml
    with: 
      directory: 'iac'

